%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.1

-ifndef(ddskerl_pb).
-define(ddskerl_pb, true).

-define(ddskerl_pb_gpb_version, "4.21.1").


-ifndef('DDSKETCH_PB_H').
-define('DDSKETCH_PB_H', true).
-record('DDSketch',
        {mapping = undefined    :: ddskerl_pb:'IndexMapping'() | undefined, % = 1, optional
         positiveValues = undefined :: ddskerl_pb:'Store'() | undefined, % = 2, optional
         negativeValues = undefined :: ddskerl_pb:'Store'() | undefined, % = 3, optional
         zeroCount = 0.0        :: float() | integer() | infinity | '-infinity' | nan | undefined % = 4, optional
        }).
-endif.

-ifndef('INDEXMAPPING_PB_H').
-define('INDEXMAPPING_PB_H', true).
-record('IndexMapping',
        {gamma = 0.0            :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 1, optional
         indexOffset = 0.0      :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2, optional
         interpolation = 'NONE' :: 'NONE' | 'LINEAR' | 'QUADRATIC' | 'CUBIC' | integer() | undefined % = 3, optional, enum IndexMapping.Interpolation
        }).
-endif.

-ifndef('STORE_PB_H').
-define('STORE_PB_H', true).
-record('Store',
        {binCounts = #{}        :: #{integer() => float() | integer() | infinity | '-infinity' | nan} | undefined, % = 1
         contiguousBinCounts = [] :: [float() | integer() | infinity | '-infinity' | nan] | undefined, % = 2, repeated
         contiguousBinIndexOffset = 0 :: integer() | undefined % = 3, optional, 32 bits
        }).
-endif.

-endif.
