name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  test:
    name: test:OTP${{matrix.otp}}
    strategy:
      fail-fast: false
      matrix:
        otp: ['27', '26', '25']
        rebar3: ['3.24.0']
    runs-on: 'ubuntu-24.04'
    env:
      OTPVER: ${{ matrix.otp }}
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: rebar3 ct
      - run: rebar3 cover
      - run: rebar3 covertool generate
      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          files: _build/test/covertool/ddskerl.covertool.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

  analysis:
    name: analysis:OTP${{matrix.otp}}
    strategy:
      fail-fast: false
      matrix:
        otp: ['27', '26', '25']
        rebar3: ['3.24.0']
    runs-on: 'ubuntu-24.04'
    env:
      OTPVER: ${{ matrix.otp }}
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - run: rebar3 compile
      - run: rebar3 lint
        if: ${{ matrix.otp == '27' }}
      - run: rebar3 fmt --check
        if: ${{ matrix.otp == '27' }}
      - run: rebar3 ex_doc
        if: ${{ matrix.otp == '27' }}
      - run: rebar3 xref
      - run: rebar3 dialyzer
